# Generated by Django 5.2.17 on 2026-08-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppCheckRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255)),
                ('dev_name', models.CharField(blank=True, max_length=255)),
                ('app_rating', models.FloatField(blank=True, null=True)),
                ('downloads', models.CharField(blank=True, max_length=50)),
                ('downloads_numeric', models.BigIntegerField(default=0)),
                ('reviews_count', models.BigIntegerField(default=0)),
                ('app_age', models.CharField(blank=True, choices=[('new', 'Less than 6 months'), ('recent', '6 months - 1 year'), ('established', '1 - 3 years'), ('veteran', 'More than 3 years')], max_length=20)),
                ('num_permissions', models.IntegerField(default=0)),
                ('sensitive_permissions', models.CharField(blank=True, max_length=500)),
                ('dev_verified', models.BooleanField(default=False)),
                ('privacy_policy', models.BooleanField(default=False)),
                ('suspicious_words', models.CharField(blank=True, max_length=500)),
                ('user_reviews', models.TextField(blank=True)),
                ('prediction', models.CharField(choices=[('Genuine', 'Genuine'), ('Suspicious', 'Suspicious')], max_length=20)),
                ('confidence', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=20)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
